version: '2.4'

services:
  shopapi:
    build:
      context: ../../
      dockerfile: automation/.docker/shopapi/Dockerfile
    restart: on-failure:5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
      - DefaultConnection=Server=MCIRSTEA\\SQLEXPRESS;Database=OnlineShop;Trusted_Connection=True;MultipleActiveResultSets=true;
    ports: 
      - ${APP_LOCAL_PORT}:80
volumes:
  db-data:
    driver: local
